name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get ninja meson
    - name: Cache build output
      uses: actions/cache@v4.1.2
      with:
        path: "build"
        key: ${{ runner.os }}-${{ hashFiles('**/meson.build') }}
        restore-keys: ${{ runner.os }}-
    - name: Configure
      run: meson setup build --buildtype=release --warning_level=highest
    - name: Compile
      run: ninja -C build
